load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//scripts:deploy.bzl", "deploy")
load("//scripts:deploy_uv.bzl", "deploy_uv")

cc_library(
    name = "streamers",
    hdrs = [
        "base_streamer.hpp",
        "depth_streamer.hpp",
        "rgb_streamer.hpp",
    ],
    copts = [
        "-std=c++17",
        "-O3",
    ],
    linkstatic = True,
    deps = [
        "//third_party/depthai:depthai-core",
        "@cppzmq",
        "@libzmq",
        "@opencv",
    ],
)

cc_binary(
    name = "oakd_streamer",
    srcs = ["main.cpp"],
    copts = [
        "-std=c++17",
        "-O3",
    ],
    linkopts = [
        "-lpthread",
        "-ldl",
        "-lm",
    ],
    deps = [
        ":streamers",
    ],
)

deploy(
    name = "deploy_oakd_streamer",
    binary = ":oakd_streamer",
)

deploy_uv(
    name = "deploy_flask_server",
    srcs = [
        "server.py",
        "//:pyproject.toml",
        "//:uv.lock",
    ],
    main_script = "server.py",
    remote_dir = "~/homebot/flask_stream",
)
