load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("//scripts:deploy.bzl", "deploy")

cc_library(
    name = "pico_interface_lib",
    hdrs = glob(["include/pico_interface/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "state_estimator",
    srcs = ["main.cpp"],
    copts = ["-std=c++20"],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        ":pico_interface_lib",
        "@opentelemetry-cpp//api",
    ],
)

cc_test(
    name = "fake_test",
    srcs = ["tests/fake_test.cpp"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        ":pico_interface_lib",
        "@googletest//:gtest_main",
        "@opentelemetry-cpp//api",
        "@opentelemetry-cpp//exporters/memory:in_memory_span_exporter",
        "@opentelemetry-cpp//exporters/ostream:ostream_span_exporter",
        "@opentelemetry-cpp//exporters/otlp:otlp_http_exporter",
        "@opentelemetry-cpp//sdk:headers",
        "@opentelemetry-cpp//sdk/src/metrics:metrics",
    ],
)

cc_binary(
    name = "test_suite",
    srcs = ["test_suite.cpp"],
    copts = ["-std=c++20"],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        ":pico_interface_lib",
    ],
)

cc_binary(
    name = "control",
    srcs = ["control.cpp"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        ":pico_interface_lib",
    ],
)

cc_binary(
    name = "calibrate_encoders",
    srcs = ["calibrate_encoders.cpp"],
    copts = ["-std=c++20"],
    data = [":control"],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        ":pico_interface_lib",
    ],
)

deploy(
    name = "deploy_state_estimator",
    binary = ":state_estimator",
)

deploy(
    name = "deploy_control",
    binary = ":control",
)

deploy(
    name = "deploy_calibrate_encoders",
    binary = ":calibrate_encoders",
)
