load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")
load("//scripts:deploy.bzl", "deploy")

cc_binary(
    name = "control",  #TODO: rename?
    srcs = ["main.cpp"],
    copts = ["-std=c++20"],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        "//infrastructure/teleop:teleop_controller_lib",
        "//mechanism/common:telemetry_defs",
        "//mechanism/hal:hardware_impl_lib",
        "//mechanism/hal:hardware_interfaces",
        "@cppzmq",
        "@libzmq",
    ],
)

cc_binary(
    name = "run_estimator",
    srcs = ["run_estimator.cpp"],
    copts = ["-std=c++20"],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
    deps = [
        "//mechanism/common:robot_config_io_lib",
        "//mechanism/common:telemetry_defs",
        "//mechanism/common:telemetry_queue_defs",
        "//mechanism/estimation:state_estimator_lib",
        "//mechanism/hal:data_reader_lib",
        "@cppzmq",
        "@libzmq",
    ],
)

cc_binary(
    name = "oakd_streamer",
    srcs = ["run_oakd_streamer.cpp"],
    copts = [
        "-std=c++17",
        "-O3",
    ],
    data = ["//mechanism/perception/stream:config"],
    linkopts = [
        "-lpthread",
        "-ldl",
        "-lm",
    ],
    deps = [
        "//mechanism/perception/stream:streamer_lib",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "test_controller",
    srcs = ["tests/test_controller.cpp"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        "//infrastructure/teleop:teleop_controller_lib",
        "@googletest//:gtest_main",
    ],
)

deploy(
    name = "deploy_control",
    binary = ":control",
)
