load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//scripts:deploy.bzl", "deploy", "deploy_uv")
load("//scripts:remote_test.bzl", "remote_cc_check", "remote_hardware_check")

filegroup(
    name = "config",
    srcs = ["vision_config.json"],
    visibility = ["//apps:__subpackages__"],
)

cc_library(
    name = "streamer_lib",
    hdrs = [
        "base_streamer.h",
        "depth_streamer.h",
        "rgb_streamer.h",
    ],
    copts = [
        "-std=c++17",
        "-O3",
    ],
    data = [":config"],
    linkstatic = True,
    visibility = ["//apps:__subpackages__"],
    deps = [
        "//third_party/depthai:depthai-core",
        "//mechanism/common:camera_config_defs",
        "@cppzmq",
        "@libzmq",
        "@opencv",
    ],
)

deploy(
    name = "deploy_oakd_streamer",
    binary = ":oakd_streamer",
    data = [":config"],
)

deploy_uv(
    name = "deploy_flask_server",
    srcs = [
        "server.py",
        "//:pyproject.toml",
        "//:uv.lock",
    ],
    data = [":config"],
    main_script = "server.py",
    remote_dir = "~/homebot/flask_stream",
)

cc_binary(
    name = "streamer_benchmark_bin",
    srcs = ["tests/streamer_benchmark.cpp"],
    deps = [
        "@google_benchmark//:benchmark",
        "@google_benchmark//:benchmark_main",
        # "//third_party:zmq", # Add this when benchmarking ZMQ
    ],
)

remote_cc_check(
    name = "streamer_benchmark",
    binary = ":streamer_benchmark_bin",
    data = [":config"],
    remote_dir = "~/homebot/bin/benchmarks",
)

remote_hardware_check(
    name = "remote_hardware_check",
    data = [
        ":config",
        "//:pyproject.toml",
        "//:uv.lock",
    ],
    test_script = "test_vision_pipeline.py",
)
